### ISSUE TITLE
Alternative variable interpolation syntax

### ISSUE THREAD

**Issue by Arkham** [intercom/ember-computed-template-string#9]
Hey there,

what do you think about using `{{variable}}` as variable interpolation syntax? So that instead of writing

`fullName: templateString("${firstName} ${lastName}")`

You would write instead

`fullName: templateString("{{firstName}} {{lastName}}")`

The motivation for that is that the addon is called `ember-computed-template-string` and this would be more consistent with handlebars variable interpolation, while using the `${variable}` syntax looks much more like ES6 variable interpolation.

**Comment by GavinJoyce** [comment]
Hey @Arkham,

The intention here was to use a syntax similar to ES6 template strings as they behave in a simliar fashion. Handlebars `{{foo}}` isn't just straight string replacement, it also escapes content in a way that this addon doesn't. It's also possible for `{{foo}}` to be a helper in a handlebars template,  not so in this addon.

I believe that the `${foo}` is the most intuitive and consistent choice
